name: DNS Monitor

on:
  schedule:
    # 6시간마다 실행 (GitHub Actions 무료 플랜 제한)
    - cron: '0 */6 * * *'
  workflow_dispatch:  # 수동 실행 가능

jobs:
  dns-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r monitoring/dns/requirements.txt
        
    - name: Run DNS monitoring
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        python monitoring/dns/checker.py 